### ISSUE TITLE
 distances(sig_network_igraph, receptors, TFs, mode = c("out"))

### ISSUE THREAD

**Issue by sailseem** [saezlab/NicheNet_Omnipath#1]
Dear developer，
   Thanks for this wonderful package，but i encounter one tiny problem when I performed the Distance_Receptor_TF <- 
  distances(sig_network_igraph, receptors, TFs, mode = c("out"))

i got error like this Error in as.igraph.vs(graph, v) : Invalid vertex names

do you know why this hanppen？ Thanks a lot

**Comment by alberto-valdeolivas** [comment]
Hello @sailseem , Sorry I missed this. Do you still have this issue?
